services:
  - type: web
    name: miro-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn index:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: HF_TOKEN
        sync: false
