
export const WorkCarousel = () => {
  return (
    <>
<section className="caro" id="work">
    <div className="track-wrap" data-slider="" style={{transform: 'translateY(-5.89062px)'}}><div className="track" style={{transform: 'translate3d(0px, 0px, 0px)'}}>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><video src="assets/work/replit-agent-3.mp4" autoPlay loop muted playsInline preload="metadata" ></video><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">Academic Integrity</p><p className="d">Ensure students submit authentic work. MIRO detects AI-generated essays with sentence-level precision.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><video src="assets/work/serve-robotics.mp4" autoPlay loop muted playsInline preload="metadata" ></video><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">Publishing & Journalism</p><p className="d">Maintain editorial standards by instantly flagging synthetic text before it goes to press.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><video src="assets/work/unstructured.mp4" autoPlay loop muted playsInline preload="metadata" ></video><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">SEO & Content Marketing</p><p className="d">Protect your domain authority. Ensure your blog posts aren't flagged as AI spam by search engines.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><img src="/assets/asset_1.avif" alt="Ouster" loading="lazy" /><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">Corporate Comms</p><p className="d">Verify that executive statements and critical internal communications are genuinely written by humans.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><video src="assets/work/ibm.mp4" autoPlay loop muted playsInline preload="metadata" ></video><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">Deep Pattern Analysis</p><p className="d">We analyze vocabulary burstiness, perplexity, and linguistic structures to find the hidden signals of LLMs.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><video src="assets/work/ordinary.mp4" autoPlay loop muted playsInline preload="metadata" ></video><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">False Positive Mitigation</p><p className="d">Our proprietary banding system prevents over-confident AI labeling, protecting authors with "Human-led" buffers.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><video src="assets/work/montefiore.mp4" autoPlay loop muted playsInline preload="metadata" ></video><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">Enterprise API</p><p className="d">Integrate MIRO directly into your CMS, LMS, or custom writing platforms with our low-latency endpoints.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><video src="assets/work/tersa.mp4" autoPlay loop muted playsInline preload="metadata" ></video><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">Visual Heatmaps</p><p className="d">Don't just get a score. See exactly which sentences triggered the AI detectors with our document overlays.</p></a>
      <a className="slide cs" href="#" rel="noopener"><div className="csm"><img src="/assets/asset_2.avif" alt="Nutrafol" loading="lazy" /><span className="reveal-cta"></span><span className="rc-clip"><span className="rc-i">View feature</span></span></div><p className="t">Real-time Scanning</p><p className="d">Analyze thousands of words in seconds. Built for speed, precision, and uncompromised accuracy.</p></a>
    </div><button type="button" className="sl-arrow prev" aria-label="Previous slides" disabled><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M19 12H5"></path><path d="m11 18-6-6 6-6"></path></svg></button><button type="button" className="sl-arrow next" aria-label="Next slides"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14"></path><path d="m13 6 6 6-6 6"></path></svg></button></div>
  </section>
    </>
  );
};
